# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 23:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityStudy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_described', models.FloatField()),
                ('metric_described', models.FloatField()),
                ('results_complete', models.FloatField()),
                ('additional_comments', models.CharField(max_length=200)),
                ('paper', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='papers.Paper')),
            ],
        ),
    ]
